services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-db_root_pass}
      MARIADB_DATABASE: ${DB_NAME:-ezmail}
      MARIADB_USER: ${DB_USER:-ezmail_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-db_password}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ] 
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    expose:
        - 3306
    ports:
      - "3306:3306"
  database_init:
    image: logiqx/mysql-client:10.5-slim-bullseye
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER:-ezmail_user}
      DB_PASS: ${DB_PASSWORD:-db_password}
      DB_NAME: ${DB_NAME:-ezmail}
    volumes:
      - "../.dev/schema.sql:/opt/schema.sql"
      - "./seed/seed.sh:/opt/seed.sh"
    command: "/bin/bash -c '/opt/seed.sh'"
  api:
    build:
      context: "../"
      dockerfile: "./docker/api/Dockerfile"
    environment:
      MYSQL_DSN: "${DB_USER:-ezmail_user}:${DB_PASSWORD:-db_password}@tcp(database:3306)/${DB_NAME:-ezmail}"
      REDIS: redis:6379
      PORT: ${API_PORT:-3000}
      NODE_ID: ${NODE_ID:-420}
      AUTH_TOKEN: ${AUTH_TOKEN}
      REDIS_EVENTS_MAX_LEN: ${REDIS_EVENTS_MAX_LEN:-2500}
      EVENTS_TOPIC: ${EVENTS_TOPIC:-topic:email.events}
      SCHEDULING_KEY: ${SCHEDULING_KEY:-queue:scheduled}
      RESCHEDULE_RETRIES: ${RESCHEDULE_RETRIES}
      RESCHEDULE_TIME_MS: ${RESCHEDULE_TIME_MS}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      REFRESH_DOMAIN_RETRIES: ${REFRESH_DOMAIN_RETRIES:-96}
      REFRESH_DOMAIN_RETRY_SEC_BETWEEN: ${REFRESH_DOMAIN_RETRY_SEC_BETWEEN:-1800}
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
  executor:
    build:
      context: "../"
      dockerfile: "./docker/executor/Dockerfile"
    environment:
      MYSQL_DSN: "${DB_USER:-ezmail_user}:${DB_PASSWORD:-db_password}@tcp(database:3306)/${DB_NAME:-ezmail}"
      REDIS: redis:6379
      PORT: ${API_PORT:-3000}
      NODE_ID: ${NODE_ID:-420}
      AUTH_TOKEN: ${AUTH_TOKEN}
      REDIS_EVENTS_MAX_LEN: ${REDIS_EVENTS_MAX_LEN:-2500}
      EVENTS_TOPIC: ${EVENTS_TOPIC:-topic:email.events}
      SCHEDULING_KEY: ${SCHEDULING_KEY:-queue:scheduled}
      RESCHEDULE_RETRIES: ${RESCHEDULE_RETRIES}
      RESCHEDULE_TIME_MS: ${RESCHEDULE_TIME_MS}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      REFRESH_DOMAIN_RETRIES: ${REFRESH_DOMAIN_RETRIES:-96}
      REFRESH_DOMAIN_RETRY_SEC_BETWEEN: ${REFRESH_DOMAIN_RETRY_SEC_BETWEEN:-1800}
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
volumes:
  db-data:
